### ISSUE TITLE
Thx but confused.

### ISSUE THREAD

**Issue by anzhehong** [XamlBrewer/UniversalOneDriveSdkSample#2]
Many thx to your onedrive demo... I run it and get perfect performance...
However, I didn't know how to implement it into my own project...very confused...I have already installed OneDrive SDK with Nuget...And then , what should I do...
Can you help me...please?
Thx a lot no matter whether you can see this issuse

**Comment by XamlBrewer** [comment]
The blog post that explains it all, is right here: http://blogs.u2u.be/diederik/post/2015/04/06/Using-the-OneDrive-SDK-in-universal-apps.aspx.

You need to register (but not necessarily publish) your app in the Windows Store, and get its Client ID.

**Comment by anzhehong** [comment]
@XamlBrewer That helps me a lot. Thx!
